version: "3"
services:
  database:
    image: spope5/medotcom-db:0.0.1
    # build: 
    #   dockerfile: Dockerfile
    #   context: ./database
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5438:5432"
    volumes: 
    - ./postgres-data:/var/lib/postgresql/data
    restart: always
  client:
    image: spope5/medotcom-client:0.0.1
    depends_on:
      - api
    # build:
    #   dockerfile: Dockerfile
    #   context: ./client
    #   target: allServer
    ports:
      - "80:80"
    restart: always
    # volumes:
    #   - ./client:/etc/nginx/html
  api:
    image: spope5/medotcom-api:latest
    depends_on:
      - database
    # build:
    #   dockerfile: Dockerfile
    #   context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - PGHOST
      - PGPORT
      - TWITTER_BEARER
    restart: always
