version: "3"
services:
  database:
    image: spope5/medotcom-db:0.0.1
    container_name: db
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5438:5432"
    restart: always
    volumes: 
    - ./postgres-data:/var/lib/postgresql/data
    # build: 
    #   dockerfile: Dockerfile
    #   context: ./database
  client:
    image: spope5/medotcom-client:latest
    container_name: client
    depends_on:
      - api
    ports:
      - "80:80"
    restart: always
    # build:
    #   dockerfile: Dockerfile
    #   context: ./client
    #   target: allServer
    # volumes:
    #   - ./client:/etc/nginx/html
  api:
    image: spope5/medotcom-api:latest
    container_name: server
    depends_on:
      - database
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - PGHOST
      - PGPORT
      - TWITTER_BEARER
    restart: always
    # build:
    #   dockerfile: Dockerfile
    #   context: "./server"
    # volumes:
    #   - ./server:/app
