version: "3"
services:
  database:
    build: 
      dockerfile: Dockerfile
      context: ./database
    ports:
      - "5438:5432"
    volumes: 
    - ./postgres-data:/var/lib/postgresql/data
  client:
    depends_on:
      - api
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "80:80"
    volumes:
      - ./client:/etc/nginx/html
  api:
    depends_on:
      - database
    build:
      dockerfile: Dockerfile
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=database
      - PGDATABASE=postgres
      - PGPASSWORD=password
      - PGPORT=5432
