version: "3"
services:
  postgres:
    build: 
      dockerfile: Dockerfile
      context: ./postgres
    ports:
      - "5438:5432"
    volumes: 
    - ./postgres-data:/var/lib/postgresql/data
  client:
    depends_on:
      - api
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "80:80"
  api:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
