insert into truths(sentence, is_true) values("I lived in a different city every month for a year", 1);
insert into truths(sentence, is_true) values("I've seen the band Phish twelve times", 1);
insert into truths(sentence, is_true) values("I want to start my own company", 1);
insert into truths(sentence, is_true) values("I tore my ACL", 1);
insert into truths(sentence, is_true) values("I've gotten fired", 1);
insert into truths(sentence, is_true) values("I'm a middle child", 1);
insert into truths(sentence, is_true) values("Haven't cut my hair in over three years", 1);
insert into truths(sentence, is_true) values("I've been to Asia", 1);
insert into truths(sentence, is_true) values("This site is in the cloud", 1);
insert into truths(sentence, is_true) values("Lived in Boston for two years", 1);
insert into truths(sentence, is_true) values("I own BTC", 1);
insert into truths(sentence, is_true) values("I've attempted the 6 12 18 24 challenge", 1);
insert into truths(sentence, is_true) values("I had 40+ different roommate in one month", 1);
insert into truths(sentence, is_true) values("I've never been to Italy", 1);
insert into truths(sentence, is_true) values("I prefer mac over pc", 1);
insert into truths(sentence, is_true) values("I work full time as a developer", 1);
insert into truths(sentence, is_true) values("I'm Lithuanian", 1);
insert into truths(sentence, is_true) values("I eat red meat", 1);
insert into truths(sentence, is_true) values("I take c4h9n3o2", 1);
insert into truths(sentence, is_true) values("This app is open source", 1);
insert into truths(sentence, is_true) values("Met my girlfriend at a Phish show", 0);
insert into truths(sentence, is_true) values("I majored in computer science", 0);
insert into truths(sentence, is_true) values("I've won an eating challenge", 0);
insert into truths(sentence, is_true) values("I'm self employed", 0);
insert into truths(sentence, is_true) values("I've been to Canada", 0);
insert into truths(sentence, is_true) values("Used to live in a pickup truck", 0);
insert into truths(sentence, is_true) values("I own my home", 0);
insert into truths(sentence, is_true) values("I built a house", 0);
insert into truths(sentence, is_true) values("Can dunk a basketball", 0);
insert into truths(sentence, is_true) values("My mixtape is out now", 0);
