insert into truths(sentence, is_true) values('I lived in a different city every month for a year', CAST(1 as BIT));
insert into truths(sentence, is_true) values('I''ve seen the band Phish twelve times', CAST(1 as BIT));
insert into truths(sentence, is_true) values('I want to start my own company', CAST(1 as BIT));
insert into truths(sentence, is_true) values('I tore my ACL', CAST(1 as BIT));                          
insert into truths(sentence, is_true) values('I''ve gotten fired', CAST(1 as BIT));                    
insert into truths(sentence, is_true) values('I''m a middle child', CAST(1 as BIT));           
insert into truths(sentence, is_true) values('Haven''t cut my hair in over three years', CAST(1 as BIT))
insert into truths(sentence, is_true) values('I''ve been to Asia', CAST(1 as BIT));                     
insert into truths(sentence, is_true) values('This site is in the cloud', CAST(1 as BIT));              
insert into truths(sentence, is_true) values('Lived in Boston for two years', CAST(1 as BIT));          
insert into truths(sentence, is_true) values('I own BTC', CAST(1 as BIT));                    
insert into truths(sentence, is_true) values('I''ve attempted the 6 12 18 24 challenge', CAST(1 as BIT));
insert into truths(sentence, is_true) values('I had 40+ different roommate in one month', CAST(1 as BIT));
insert into truths(sentence, is_true) values('I''ve never been to Italy', CAST(1 as BIT));              
insert into truths(sentence, is_true) values('I prefer mac over pc', CAST(1 as BIT));                   
insert into truths(sentence, is_true) values('I work full time as a developer', CAST(1 as BIT));        
insert into truths(sentence, is_true) values('I''m Lithuanian', CAST(1 as BIT));                
insert into truths(sentence, is_true) values('I eat red meat', CAST(1 as BIT));                 
insert into truths(sentence, is_true) values('I take c4h9n3o2', CAST(1 as BIT));                
insert into truths(sentence, is_true) values('This app is open source', CAST(1 as BIT));
insert into truths(sentence, is_true) values('Met my girlfriend at a Phish show', CAST(0 as BIT));
insert into truths(sentence, is_true) values('I majored in computer science', CAST(0 as BIT));    
insert into truths(sentence, is_true) values('I''ve won an eating challenge', CAST(0 as BIT));    
insert into truths(sentence, is_true) values('I''m self employed', CAST(0 as BIT));               
insert into truths(sentence, is_true) values('I''ve been to Canada', CAST(0 as BIT));         
insert into truths(sentence, is_true) values('Used to live in a pickup truck', CAST(0 as BIT));
insert into truths(sentence, is_true) values('I own my home', CAST(0 as BIT));                 
insert into truths(sentence, is_true) values('I built a house', CAST(0 as BIT));               
insert into truths(sentence, is_true) values('Can dunk a basketball', CAST(0 as BIT));         
insert into truths(sentence, is_true) values('My mixtape is out now', CAST(0 as BIT)); 
